export const PARSE_EVENTS = {
  APP_OPEN: 'app.open',
  USER_SIGNUP: 'new.user.create',
  LOGIN: 'user.login',
  LOGOUT: 'user.logout',
  MYSTUDY: 'click.mystudy',
  CLASSROOM: 'click.classroom',
  JOIN_CLASSROOM: 'click.join.classroom',
  LEARNING_JOURNEY: 'click.class.card.lj',
  MY_PROFICIENCY: 'click.class.card.my.proficiency',
  CLASS_ACTIVITY: 'click.class.card.ca',
  CLASS_ACTIVITY_CONTENT_PLAY: 'click.ca.content.play',
  NAVBAR_LEARNING_JOURNEY: 'click.navbar.lj',
  NAVBAR_MY_PROFICIENCY: 'click.navbar.my.proficiency',
  NAVBAR_CLASS_ACTIVITY: 'click.class.activity',
  NAVBAR_DASHBOARD: 'click.class.dashboard',
  NAVBAR_CLASS_INFO: 'click.class.info',
  LIBRARY: 'click.library',
  MILESTONE_PROGRESS_REPORT: 'click.milestone.progress.report',
  PAGE_VIEW: 'page.view',
  NOTIFICATION: 'click.notification',
  COLLECTION_REPORT: 'view.collection.report',
  VIEW_LESSON_PLAN: 'view.lesson.plan',
  CONTENT_BUILDER_COURSE: 'click.content.builder.course',
  CONTENT_BUILDER_COLLECTION: 'click.content.builder.collection',
  CONTENT_BUILDER_ASSESSMENT: 'click.content.builder.assessment',
  CONTENT_BUILDER_OFFLINE_ACTIVITY: 'click.content.builder.offline.activity',
  CONTENT_BUILDER_RESOURCES: 'click.content.builder.resources',
  CONTENT_BUILDER_QUESTION: 'click.content.builder.questions',
  CONTENT_BUILDER_RUBRICS: 'click.content.builder.rubrics',
  ASSESSMENT_REPORT: 'view.assessment.report',
  SHOW_MORE_CLASSROOM: 'view.more.classroom',
  SHOW_LESS_CLASSROOM: 'view.less.classroom',
  SHOW_MORE_COURSE: 'view.more.course',
  SHOW_LESS_COURSE: 'view.less.course',
  EDIT_COURSE: 'edit.course',
  DELETE_CLASS_ROOM: 'delete.classroom',
  ARCHIVE_CLASS_ROOM: 'archive.classroom',
  VIEW_MILESTONE: 'view.milestone',
  VIEW_COURSE_MAP: 'view.course.map',
  STUDY_RECOMMENDED_COURSE: 'study.recommended.course',
  EXPAND_RECOMMENDED_COURSE: 'expand.recommended.course',
  ADD_STUDENT_CLASS_SETTING: 'add.student.class.setting',
  INSPECT_COMPENTENCY: 'inspect.compentency',
  SEARCH_CA: 'search.ca',
  ASSIGN_ACTIVITY: 'assign.activity',
  RESCHEDULE_ACTIVITY_CA: 'reschedule.activity.ca',
  GO_LIVE_CA: 'go.live.ca',
  ADD_DATA_CA: 'add.data.ca',
  VIEW_REPORT_CA: 'view.report.ca',
  ADD_COLLABATOR_CLASS_SETTING: 'add.collabator.class.setting',
  CONFIRM_NEXT: 'play.next',
  PLAYER_EXIT: 'play.exit',
  COURSE_MAP_LESSON_PLAY: 'course.map.play',

  CLICK_GROWTH_LEARNING_CHALLENGES: 'click.growth.learning.challenges',
  CLICK_GROWTH_SUGGESTION_COLLECTION: 'click.growth.suggestion.collection',
  CLICK_GROWTH_SUGGESTION_ASSESSMENT: 'click.growth.suggestion.assessment',
  CLICK_GROWTH_TENANT_LIBRARY: 'click.growth.tenant.library',
  CLICK_GROWTH_GOORU_CATALOG_COLLECTION: 'click.growth.mycontent.collection',
  CLICK_GROWTH_GOORU_CATALOG_ASSESSMENT: 'click.growth.mycontent.assessment',
  CLICK_GROWTH_MYCONTENT_COLLECTION: 'click.growth.mycontent.collection',
  CLICK_GROWTH_MYCONTENT_ASSESSMENT: 'click.growth.mycontent.assessment',
  CLICK_GROWTH_PROFILE: 'click.growth.profile',
  CLICK_INDIVIDUAL_REPORTS: 'click.individual.reports',
  CLICK_INDIVIDUAL_REPORTS_OVERVIEW: 'click.individual.reports.overview',
  CLICK_INDIVIDUAL_REPORTS_DATE: 'click.individual.reports.date',
  CLICK_INDIVIDUAL_REPORTS_DOWNLOAD: 'click.individual.reports.download',
  CLICK_INDIVIDUAL_REPORTS_DOWNLOAD_CSV:
    'click.individual.reports.download.csv',
  CLICK_INDIVIDUAL_REPORTS_DOWNLOAD_PDF:
    'click.individual.reports.download.pdf',
  CLICK_INDIVIDUAL_STUDENTS_ASSESSMENT: 'click.individual.students.assessment',
  CLICK_PO_DATE_PRE_ARROW: 'click.po.date.pre.arrow',
  CLICK_PO_DATE_NEXT_ARROW: 'click.po.date.next.arrow',
  CLICK_PROFICIENCY_CHARTS_GRADE_RANGE_COLLECTION:
    'click.proficiency.charts.grade.range.collection',
  CLICK_PROFICIENCY_CHARTS_GRADE_RANGE_ASSESSMENT:
    'click.proficiency.charts.grade.range.assessment',
  CLICK_CA_ASSESSMENT: 'click.ca.assessment',
  CLICK_CA_COLLECTION: 'click.ca.collection',
  CLICK_CA_OFFLINE_ACTIVITY: 'click.ca.offline.activity',
  CLICK_CA_VIDEO_CONFERENCE: 'click.ca.video.conference',
  CLICK_CA_SHOW_ALL: 'click.ca.show.all',
  CLICK_CA_SHOW_SCOPE_SEQUENCE: 'click.ca.show.scope.sequence',
  CLICK_CA_SHOW_SCOPE_SEQUENCE_SCHEDULE:
    'click.ca.show.scope.sequence.schedule',
  CLICK_CA_SHOW_SCOPE_SEQUENCE_SCHEDULE_ADD_ACTIVITY:
    'click.ca.show.scope.sequence.schedule.add.activity',
  CLICK_CA_SHOW_PREVIEW_SCOPE_SEQUENCE_CARD:
    'click.ca.preview.show.scope.sequence.card',
  CLICK_CA_SHOW_PREVIEW_SCOPE_SEQUENCE_CARD_PLAY:
    'click.ca.preview.show.scope.sequence.card.play',
  CLICK_CA_SHOW_PREVIEW_SCOPE_SEQUENCE_CARD_DOWNLOAD:
    'click.ca.preview.show.scope.sequence.card.download',
  CLICK_CA_SHOW_PREVIEW_SCOPE_SEQUENCE_CARD_CORRECT_ANSWER:
    'click.ca.preview.show.scope.sequence.card.correct.answer',
  CLICK_CA_ITEM_GRADE: 'click.ca.item.grade',
  CLICK_CA_ITEM_GRADE_SCORE: 'click.ca.item.grade.score',
  CLICK_CA_ITEM_GRADE_RUBRIC_LEVEL: 'click.ca.item.grade.rubric.level',
  CLICK_CA_ITEM_GRADE_RUBRIC_CLEAR: 'click.ca.item.grade.rubric.clear',
  CLICK_CA_ITEM_GRADE_RUBRIC_COMMENT: 'click.ca.item.grade.rubric.comment',
  CLICK_CA_ITEM_GRADE_SUBMIT: 'click.ca.item.grade.rubric.sumbit',
  CLICK_CA_ITEM_GRADE_SELECT_USER: 'click.ca.item.grade.rubric.select.user',
  CLICK_CA_DAILY_VIEW: 'click.ca.daily.view',
  CLICK_CA_DAILY_VIEW_VIDEO: 'click.ca.daily.view.video',
  CLICK_CA_DAILY_ENABLE_VIDEO_CONF: 'click.ca.daily.enable.video.conf',
  CLICK_CA_DAILY_VIDEO_CONF_UPDATE: 'click.ca.daily.video.conf.update',
  CLICK_CA_DAILY_VIDEO_CONF_START: 'click.ca.daily.video.conf.start',
  CLICK_CA_DAILY_VIEW_ACTIVATE: 'click.ca.daily.view.activate',
  CLICK_CA_DAILY_VIEW_MASTERY: 'click.ca.daily.view.mastery',
  CLICK_CA_DAILY_VIEW_GOLIVE: 'click.ca.daily.view.golive',
  CLICK_CA_DAILY_VIEW_DELETE: 'click.ca.daily.view.delete',
  CLICK_CA_DAILY_VIEW_USER: 'click.ca.daily.view.user',
  CLICK_CA_DAILY_VIEW_COMPEDENCY: 'click.ca.daily.view.compedency',
  CLICK_CA_WEEKLY_VIEW: 'click.ca.weekly.view',
  CLICK_CA_WEEKLY_VIEW_VIDEO: 'click.ca.weekly.view.video',
  CLICK_CA_WEEKLY_ENABLE_VIDEO_CONF: 'click.ca.weekly.enable.video.conf',
  CLICK_CA_WEEKLY_VIDEO_CONF_UPDATE: 'click.ca.weekly.video.conf.update',
  CLICK_CA_WEEKLY_VIDEO_CONF_START: 'click.ca.weekly.video.conf.start',
  CLICK_CA_WEEKLY_VIEW_ACTIVATE: 'click.ca.weekly.view.activate',
  CLICK_CA_WEEKLY_VIEW_MASTERY: 'click.ca.weekly.view.mastery',
  CLICK_CA_WEEKLY_VIEW_GOLIVE: 'click.ca.weekly.view.golive',
  CLICK_CA_WEEKLY_VIEW_DELETE: 'click.ca.weekly.view.delete',
  CLICK_CA_WEEKLY_VIEW_USER: 'click.ca.weekly.view.user',
  CLICK_CA_WEEKLY_VIEW_COMPEDENCY: 'click.ca.weekly.view.compedency',
  CLICK_CA_MONTHLY_VIEW: 'click.ca.monthly.view',
  CLICK_CA_MONTHLY_VIEW_VIDEO: 'click.ca.monthly.view.video',
  CLICK_CA_MONTHLY_ENABLE_VIDEO_CONF: 'click.ca.monthly.enable.video.conf',
  CLICK_CA_MONTHLY_VIDEO_CONF_UPDATE: 'click.ca.monthly.video.conf.update',
  CLICK_CA_MONTHLY_VIDEO_CONF_START: 'click.ca.monthly.video.conf.start',
  CLICK_CA_MONTHLY_VIEW_ACTIVATE: 'click.ca.monthly.view.activate',
  CLICK_CA_MONTHLY_VIEW_MASTERY: 'click.ca.monthly.view.mastery',
  CLICK_CA_MONTHLY_VIEW_GOLIVE: 'click.ca.monthly.view.golive',
  CLICK_CA_MONTHLY_VIEW_DELETE: 'click.ca.monthly.view.delete',
  CLICK_CA_MONTHLY_VIEW_USER: 'click.ca.monthly.view.user',
  CLICK_CA_MONTHLY_VIEW_COMPEDENCY: 'click.ca.monthly.view.compedency',
  CLICK_NOTIFICATIONS_SHOW_MORE: 'click.notification.show.more',
  CLICK_NOTIFICATIONS_ITEM: 'click.notification.item',
  CLICK_CS_ADD_STUDENT: 'click.cs.add.student',
  CLICK_CS_SELECT_STUDENT: 'click.cs.select.student',
  CLICK_CS_SEARCH_BY: 'click.cs.search.by',
  CLICK_CS_SEARCH_STUDENT: 'click.cs.search.student',
  CLICK_CS_DELETE_STUDENT: 'click.cs.delete.student',
  CLICK_CS_CHOOSE_COLUMNS: 'click.cs.choose.columns',
  CLICK_CS_IMPERSONATE: 'click.cs.impersonate',
  CLICK_CS_EDIT_CLASS_NAME: 'click.cs.edit.class.name',
  CLICK_CS_MULTI_GRADE_SAVE: 'click.cs.multi.grade.save',
  CLICK_LJ_IS_MILESTONE: 'click.lj.is.milestone',
  CLICK_LJ_IS_MILESTONE_LESSON: 'click.lj.is.milestone.lesson',
  CLICK_LJ_IS_MILESTONE_USER: 'click.lj.is.milestone.user',
  CLICK_LJ_IS_MILESTONE_LESSON_USER: 'click.lj.is.milestone.lesson.user',
  CLICK_LJ_IS_MILESTONE_REPORT: 'click.lj.is.milestone.report',
  CLICK_LJ_IS_MILESTONE_GRID_VIEW: 'click.lj.is.milestone.grid.view',
  CLICK_LJ_IS_MILESTONE_LIST_VIEW: 'click.lj.is.milestone.list.view',
  CLICK_LJ_IS_MILESTONE_TIMESPEND: 'click.lj.is.milestone.timespend',
  CLICK_LJ_IS_MILESTONE_REACTION: 'click.lj.is.milestone.reaction',
  CLICK_LJ_IS_SHOW_COURSE_MAP: 'click.lj.is.show.course.map',
  CLICK_LJ_IS_SHOW_LESSON_PLAN: 'click.lj.is.show.lesson.plan',
  CLICK_LJ_IS_MILESTONE_LESSON_CFU: 'click.lj.is.milestone.lesson.cfu',
  CLICK_LJ_IS_CHART: 'click.lj.is.chart',
  CLICK_LJ_IS_CHART_INFO: 'click.lj.is.chart.info',
  CLICK_LJ_IS_CHART_REPORT: 'click.lj.is.chart.report',
  CLICK_LJ_IS_CHART_REPORT_SUGGESTION: 'click.lj.is.chart.report.suggestion',
  CLICK_LJ_IS_CHART_REPORT_SUGGESTION_REPORT:
    'click.lj.is.chart.report.suggestion.report',
  CLICK_LJ_IS_MILESTONE_CARD: 'click.lj.is.milestone.card',
  CLICK_LJ_IS_LESSON_CARD: 'click.lj.is.lesson.card',
  CLICK_LJ_IS_COLLECTION_PREVIEW: 'click.lj.is.collection.preview',
  CLICK_LJ_IS_MILESTONE_LESSON_CFU_REPORT:
    'click.lj.is.milestone.lesson.cfu.report',
  CLICK_LJ_IS_MILESTONE_LESSON_SHOW_PERFORMANCE:
    'click.lj.is.milestone.lesson.show.performance',
  CLICK_LJ_IS_UNIT_REPORT_PRE: 'click.lj.is.unit.report.pre',
  CLICK_LJ_IS_UNIT_REPORT_NEXT: 'click.lj.is.unit.report.next',
  CLICK_LJ_IS_MILESTONE_GO_LIVE: 'click.lj.is.milestone.go.live',
  CLICK_LJ_IS_MILESTONE_GO_LIVE_REPORT: 'click.lj.is.milestone.go.live.report',
  CLICK_LJ_IS_MILESTONE_GO_LIVE_VIEW: 'click.lj.is.milestone.go.live.view',
  CLICK_GROWTH_SUGGESTION_FILTER: 'click.growth.suggestion.filter',
  CLICK_GROWTH_SUGGESTION_APPLY_FILTER: 'click.growth.suggestion.apply.filter',
  CLICK_GROWTH_SUGGESTION_SEARCH_STUDENT:
    'click.growth.suggestion.search.student',
  CLICK_PROFICIENCY_CHARTS_DOMAIN: 'click.proficiency.charts.domain',
  CLICK_PROFICIENCY_CHARTS_COMPETENCIES:
    'click.proficiency.charts.competencies',
  CLICK_PROFICIENCY_CHARTS_SUGGESTION_PRE:
    'click.proficiency.charts.suggestion.pre',
  CLICK_PROFICIENCY_CHARTS_SUGGESTION: 'click.proficiency.charts.suggestion',
  CLICK_PROFICIENCY_CHARTS_SELECT_MONTH:
    'click.proficiency.charts.select.month',
  CLICK_STUDENT_NAVBAR_SUGGESTION: 'click.student.navbar.suggestion',
  CLICK_STUDENT_NAVBAR_SUGGESTION_SYSTEM:
    'click.student.navbar.suggestion.system',
  CLICK_STUDENT_NAVBAR_SUGGESTION_TEACHER:
    'click.student.navbar.suggestion.teacher',
  CLICK_STUDENT_NAVBAR_SUGGESTION_FILTER:
    'click.student.navbar.suggestion.filter',
  CLICK_STUDENT_NAVBAR_SUGGESTION_FILTER_SELECTED:
    'click.student.navbar.suggestion.filter.selected',
  CLICK_STUDENT_DASHBOARD_PERFORMANCE_OVERVIEW:
    'click.student.dashboard.performance.overview ',
  CLICK_STUDENT_DASHBOARD_ACTIVITY_PLAY:
    'click.student.dashboard.activity.play',
  CLICK_STUDENT_CA_DAILY: 'click.student.ca.daily',
  CLICK_STUDENT_CA_WEEKLY: 'click.student.ca.weekly',
  CLICK_STUDENT_CA_MONTHLY: 'click.student.ca.monthly',
  CLICK_STUDENT_STUDY_TIMER: 'click.student.study.timer',
  CLICK_STUDENT_LJ_UNIT: 'click.student.lj.unit',
  CLICK_STUDENT_LJ_LESSON: 'click.student.lj.lesson',
  CLICK_STUDENT_LJ_LESSON_REPORT: 'click.student.lj.lesson.report',
  CLICK_STUDENT_LJ_UNIT_INFO: 'click.student.lj.unit.info',
  CLICK_STUDENT_LJ_LESSON_INFO: 'click.student.lj.lesson.info',
  CLICK_STUDENT_LJ_PLAY: 'click.student.lj.play',
  CLICK_STUDENT_LJ_LESSON_PERFORMANCE: 'click.student.lj.lesson.performance',
  CLICK_STUDENT_LJ_PROGRESS_VIEW: 'click.student.lj.progress.view',
  CLICK_STUDY_PLAYER_SUGGESTION_NOTNOW: 'click.study.player.suggestion.notnow',
  CLICK_STUDY_PLAYER_SUGGESTION_CONTINUE:
    'click.study.player.suggestion.continue',
  CLICK_STUDENT_PORTFOLIO_FILTER: 'click.student.portfolio.filter',
  CLICK_STUDENT_PORTFOLIO_APPLY_FILTER: 'click.student.portfolio.apply.filter',
  CLICK_STUDENT_CA_TAB: 'click.student.ca.tab',
  CLICK_STUDENT_CA_ITEM_TO_GRADE_TAB: 'click.student.ca.item.to.grade.tab',
  CLICK_STUDENT_CA_ASSESSMENT_REPORT: 'click.student.ca.assessment.report',
  CLICK_STUDENT_CA_COLLECTION_REPORT: 'click.student.ca.collection.report',
  CLICK_STUDENT_CA_TODAY: 'click.student.ca.today',
  CLICK_STUDENT_LJ_INFO: 'click.student.lj.info',
  CLICK_STUDENT_LJ_MILESTONE_REPORT: 'click.student.lj.milestone.report',
  CLICK_STUDENT_LJ_MILESTONE_ITEM: 'click.student.lj.milestone.item',
  CLICK_STUDENT_LJ_MILESTONE_ITEM_INFO: 'click.student.lj.milestone.item.info',
  CLICK_STUDENT_LJ_MILESTONE_ITEM_PLAY: 'click.student.lj.milestone.item.play',
  CLICK_STUDENT_LJ_MILESTONE_ITEM_REPORT:
    'click.student.lj.milestone.item.report',
  CLICK_STUDENT_HOME_CLASSROOMS: 'click.student.home.classrooms',
  CLICK_STUDENT_HOME_INDIVIDUAL: 'click.student.home.individual',
  CLICK_STUDENT_HOME_MY_NAVIGATOR: 'click.student.my.navigator',
  CLICK_PROFICIENCY_CHARTS_GRADE_RANGE_OFFLINE:
    'click.proficiency.charts.grade.range.offline',
  CLICK_STUDENT_NAVBAR_SUGGESTION_PLAY: 'click.student.navbar.suggestion.play',
  CLICK_STUDENT_NAVBAR_SUGGESTION_REPORT:
    'click.student.navbar.suggestion.report',
  CLICK_STUDY_HOME_START_STUDYING: 'click.study.home.start.studying',
  CLICK_STUDY_HOME_SEE_ALL_COURSE: 'click.study.home.see.all.course',
  CLICK_PROFICIENCY_CHARTS_SUGGESTION_PLAY:
    'click.proficiency.charts.suggestion.play',
  CLICK_PROFICIENCY_CHARTS_DOMAIN_COMPTENCY:
    'click.proficiency.charts.domain.compedency',
  CLICK_PROFICIENCY_CHARTS_DOWNLOAD: 'click.proficiency.charts.download',
  CLICK_CURRENTLY_TEACHING: 'click.currently.teaching',
  CLICK_INCOMPLETE_SETUP: 'click.incomplete.setup',
  CLICK_ARCHIVED_CLASSROOMS: 'click.archived.classrooms',
  CLICK_CS_UPDATE_THUMBNAIL: 'click.cs.update.thumbnail',
  CLICK_CS_DELETE_THUMBNAIL: 'click.cs.delete.thumbnail',
  CLICK_NAVBAR_ADVANCED: 'click.navbar.advanced',
  CLICK_STUDY_HOME_WHATS_NEW: 'click.study.home.whats.new',
  CLICK_PO_CLASS_PROGRESS_DATE: 'click.po.class.progress.date',
  CLICK_PO_CLASS_PROGRESS_DATE_DAILY: 'click.po.class.progress.date.daily',
  CLICK_PO_CLASS_PROGRESS_DATE_WEEKLY: 'click.po.class.progress.date.weekly',
  CLICK_PO_CLASS_PROGRESS_DATE_MONTHLY: 'click.po.class.progress.date.monthly',
  CLICK_PO_CLASS_PROGRESS_DATE_DATERANGE:
    'click.po.class.progress.date.daterange',
  CLICK_PO_CLASS_PROGRESS_DATE_DATERANGE_SUBMIT:
    'click.po.class.progress.date.daterange.submit',
  CLICK_PO_CLASS_PROGRESS_DATE_ALLTIME: 'click.po.class.progress.date.alltime',
  CLICK_PO_CLASS_PROGRESS_USER_CLOSE: 'click.po.class.progress.user.close',
  CLICK_GROWTH_SUGGESTION_COLLECTION_PLAY:
    'click.growth.suggestion.collection.play',
  CLICK_GROWTH_SUGGESTION_COLLECTION_SUGGEST_STUDENT:
    'click.growth.suggestion.collection.suggest.student',
  CLICK_GROWTH_SUGGESTION_COLLECTION_SCHEDULE_LATER:
    'click.growth.suggestion.collection.schedule.later',
  CLICK_GROWTH_SUGGESTION_COLLECTION_ADD_TODAY_CLASS:
    'click.growth.suggestion.collection.add.today.class',
  CLICK_GROWTH_SUGGESTION_ASSESSMENT_PLAY:
    'click.growth.suggestion.assessment.play',
  CLICK_GROWTH_SUGGESTION_ASSESSMENT_SUGGEST_STUDENT:
    'click.growth.suggestion.assessment.suggest.student',
  CLICK_GROWTH_SUGGESTION_ASSESSMENT_SCHEDULE_LATER:
    'click.growth.suggestion.assessment.schedule.later',
  CLICK_GROWTH_SUGGESTION_ASSESSMENT_ADD_TODAY_CLASS:
    'click.growth.suggestion.assessment.add.today.class',
  CLICK_PO_DATA_BY_MILESTONE: 'click.po.data.by.milestone',
  CLICK_PO_DATA_BY_MILESTONE_SELECTED: 'click.po.data.by.milestone.selected',
  CLICK_PO_DATA_BY_MILESTONE_SORT: 'click.po.data.by.milestone.sort',
  CLICK_PO_DATA_BY_MILESTONE_ALL: 'click.po.data.by.milestone.all',
  CLICK_PO_DATA_BY_MILESTONE_CLEAR: 'click.po.data.by.milestone.clear',
  CLICK_PO_DATA_BY_MILESTONE_BACK: 'click.po.data.by.milestone.back',
  CLICK_PO_DATA_BY_DIAGNOATIC: 'click.po.data.by.diagnostic',
  CLICK_PO_DATA_BY_DIAGNOATIC_BY_DOMAIN:
    'click.po.data.by.diagnostic.by.domain',
  CLICK_PO_DATA_BY_DIAGNOATIC_BY_ASSESSMENT:
    'click.po.data.by.diagnostic.by.assessment',
  CLICK_PO_DATA_BY_DIAGNOATIC_BY_SELLECTED_DOMAIN:
    'click.po.data.by.diagnostic.by.selected.domain',
  CLICK_PO_DATA_BY_DIAGNOATIC_BY_SELLECTED_ASSESSMENT:
    'click.po.data.by.diagnostic.by.selected.assessment',
  CLICK_PO_DATA_BY_DIAGNOATIC_BY_DOWNLOAD:
    'click.po.data.by.diagnostic.download',
  CLICK_PO_DATA_BY_DIAGNOATIC_BY_DOWNLOAD_CSV:
    'click.po.data.by.diagnostic.download.csv',
  CLICK_PO_DATA_BY_DIAGNOATIC_BY_DOWNLOAD_PDF:
    'click.po.data.by.diagnostic.download.pdf',
  CLICK_PO_DATA_BY_DIAGNOATIC_SEE_RESPONSE:
    'click.po.data.by.diagnostic.see.response',
  CLICK_PO_DATA_BY_DIAGNOATIC_QUESTION: 'click.po.data.by.diagnostic.question',
  CLICK_PO_DATA_BY_DIAGNOATIC_EXPAND: 'click.po.data.by.diagnostic.expand',
  CLICK_PO_DATA_BY_DIAGNOATIC_BACK: 'click.po.data.by.diagnostic.back',
  CLICK_LJ_MILESTONE_REPORT_SUGGEST_COLLECTION_PLAY:
    'click.lj.milestone.report.suggest.collection.play',
  CLICK_LJ_MILESTONE_REPORT_SUGGEST_COLLECTION_ADD:
    'click.lj.milestone.report.suggest.collection.add',
  CLICK_LJ_MILESTONE_REPORT_SUGGEST_ASSESSMENT_PLAY:
    'click.lj.milestone.report.suggest.assessment.play',
  CLICK_LJ_MILESTONE_REPORT_SUGGEST_ASSESSMENT_ADD:
    'click.lj.milestone.report.suggest.assessment.add',
  CLICK_CA_SHOW_SCOPE_SEQUENCE_EXPAND: 'click.ca.show.scope.sequence.expand',
  CLICK_CA_SHOW_SCOPE_SEQUENCE_SELECTED:
    'click.ca.show.scope.sequence.selected',
  CLICK_CA_ITEM_GRADE_SORT_BY: 'click.ca.item.grade.sort.by',
  CLICK_CA_ITEM_GRADE_OFFLINE_SUBMISSION:
    'click.ca.item.grade.offline.submissions',
  CLICK_CA_ITEM_GRADE_OFFLINE_UPLOADS: 'click.ca.item.grade.offline.uploads',
  CLICK_CA_ITEM_GRADE_OFFLINE_URLS: 'click.ca.item.grade.offline.urls',
  CLICK_CA_ITEM_GRADE_OFFLINE_FILE_ATTACHED:
    'click.ca.item.grade.offline.file.attached',
  CLICK_CS_TEACHER_ADD: 'click.cs.teacher.add',
  CLICK_CS_TEACHER_DONE: 'click.cs.teacher.done',
  CLICK_CS_TEACHER_CANCEL: 'click.cs.teacher.cancel',
  CLICK_CS_MULTI_GRADE_SELECTED: 'click.cs.multi.grade.selected',
  CLICK_CS_ENABLE_COMPEDENCY_MASTERY: 'click.cs.enable.compedency.mastery',
  CLICK_CS_PRESENR_DIAGNOSTIC: 'click.cs.present.diagnostic',
  CLICK_CS_SHOW_CORRECT_ANSWER: 'click.cs.show.correct.answer',
  CLICK_CS_UPLOAD_EVIDENCE: 'click.cs.upload.evidence',
  CLICK_CS_STUDENT_ACTIVATE: 'click.cs.student.activate',
  CLICK_CS_LANGUAGE_INSTRUCTION: 'click.cs.language.instruction',
  CLICK_CS_REPORT: 'click.ca.report',
  CLICK_CS_CLASS_REPORT: 'click.ca.class.report',
  CLICK_CS_ACTIVITY_REPORT: 'click.ca.activity.report',
  CLICK_CS_ACTIVITY_REPORT_UPLOAD_DATA: 'click.ca.activity.report.upload.data',
  CLICK_CS_ACTIVITY_REPORT_UPLOAD_DATA_STUDENT:
    'click.ca.activity.report.upload.data.student',
  CLICK_CS_ACTIVITY_REPORT_UPLOAD_DATA_UPDATE_SCORE:
    'click.ca.activity.report.upload.data.update.core',
  CLICK_CS_ACTIVITY_REPORT_UPLOAD_DATA_Q_SCORE:
    'click.ca.activity.report.upload.data.q.core',
  CLICK_CS_ACTIVITY_REPORT_UPLOAD_DATA_NEXT:
    'click.ca.activity.report.upload.data.next',
  CLICK_CS_ACTIVITY_REPORT_STUDENT_REPORT:
    'click.ca.activity.report.student.report',
  CLICK_CS_ACTIVITY_REPORT_STUDENT_REPORT_CLEAR:
    'click.ca.activity.report.student.report.clear',
  CLICK_CS_ACTIVITY_REPORT_STUDENT_REPORT_PERF:
    'click.ca.activity.report.student.report.perf',
  CLICK_LJ_REPORT: 'click.lj.report',
  CLICK_LJ_SELECT_STUDENT: 'click.lj.select.student',
  CLICK_LJ_SELECT_STUDENT_CLEAR: 'click.lj.select.student.clear',
  CLICK_LJ_SELECT_STUDENT_REPORT: 'click.lj.select.student.report',
  CLICK_LJ_UNIT: 'click.lj.unit',
  CLICK_LJ_UNIT_REPORT: 'click.lj.unit.report',
  CLICK_LJ_LESSON: 'click.lj.lesson',
  CLICK_LJ_LESSON_REPORT: 'click.lj.lesson.report',
  CLICK_LJ_LESSON_LIVE: 'click.lj.lesson.live',
  CLICK_LJ_LESSON_ASSIGN: 'click.lj.lesson.assign',
  CLICK_LJ_LESSON_INFO: 'click.lj.lesson.info',
  CLICK_CA_PREVIEW: 'click.ca.preview',
  CLICK_CA_MARK_AS_CLOSED: 'click.ca.mark.as.closed',
  CLICK_CA_RESCHEDULE: 'click.ca.reschedule',
  CLICK_CA_UPDATE_TIMESPENT: 'click.ca.update.timespent',
  CLICK_CA_ADD_DATA_CONFIR_UPDATE_TIMESPENT:
    'click.ca.add.data.confirm.timespent',
  CLICK_CA_APPLY_FILTER: 'click.ca.apply.filter',
  CLICK_DASHBOARD_LEARNING_TOOL: 'click.dashboard.learning.tool',
  CLICK_HEADER_LEARNING_TOOL: 'click.header.learning.tool',
  CLICK_CA_DIAG_ASSESSMENT_SUGGEST: 'click.ca.diag.assessment.suggest',
  CLICK_LJ_UNIT_CONTENT_VISIBILITY: 'click.lj.unit.content.visibility',
  CLICK_LJ_LESSON_CONTENT_VISIBILITY: 'click.lj.lesson.content.visibility',
  CLICK_PO_STUDENT_PROGRESS: 'click.po.student.progress',
  CLICK_PO_CLASS_PROGRESS: 'click.po.class.progress',
  CLICK_PO_CLASS_PROGRESS_CSV_DOWNLOAD: 'click.po.class.progress.csv.download',
  CLICK_PO_CLASS_PROGRESS_PDF_DOWNLOAD: 'click.po.class.progress.pdf.download',
  CLICK_CLASS_PROFICIENCY_DOWNLOAD: 'click.class.proficiency.download',
  CLICK_CLASS_PROFICIENCY_SEARCH_COURSE:
    'click.class.proficiency.search.course',
  CLICK_CLASS_PROFICIENCY_SEARCH_UNIT: 'click.class.proficiency.search.unit',
  CLICK_CLASS_PROFICIENCY_SEARCH_LESSON:
    'click.class.proficiency.search.lesson',
  CLICK_CLASS_PROFICIENCY_SEARCH_COLLECTION:
    'click.class.proficiency.search.collection',
  CLICK_CLASS_PROFICIENCY_SEARCH_ASSESSMENT:
    'click.class.proficiency.search.assessment',
  CLICK_CLASS_PROFICIENCY_SEARCH_QUESTION:
    'click.class.proficiency.search.question',
  CLICK_CLASS_PROFICIENCY_SEARCH_RESOURCE:
    'click.class.proficiency.search.resource',
  CLICK_CLASS_PROFICIENCY_SEARCH_RUBRIC:
    'click.class.proficiency.search.rubric',
  CLICK_MYCONTENT_ADD_COURSE: 'click.mycontent.add.course',
  CLICK_CREATE_COLLECTION: 'click.create.collection',
  CLICK_CREATE_ASSESSMENT: 'click.create.assessment',
  CLICK_CREATE_COURSE: 'create.course',
  CLICK_CREATE_QUESTION: 'create.question',
  CLICK_CREATE_RUBRIC: 'create.rubric',
  SAVE_COLLECTION: 'save.collection',
  SAVE_ASSESSMENT: 'save.assessment',
  COURSE_DELETE: 'course.delete',
  COLLECTION_DELETE: 'collection.delete',
  ASSESSMENT_DELETE: 'assessment.delete',
  QUESTION_DELETE: 'question.delete',
  RESOURCE_DELETE: 'resource.delete',
  RUBRIC_DELETE: 'rubric.delete',
  OA_ACTIVITY: 'oa.delete',
  PROFICIENCY_AUDIO_NEXT: 'proficiency.audio.next',
  PROFICIENCY_AUDIO_SKIP_ALL: 'proficiency.audio.skip.all',
  SHOW_ROUTE: 'show.route',
  PROFICIENCY_SKIP_AUDIO: 'proficiency.skip.audio',
  START_STUDING: 'start.studing',
  LEARNING_CHALLENGE_SUGGEST_TO_STUDENT:
    'learning.challenge.suggest.to.student',
  CLICK_NOT_SETUP_BACK: 'click.not.setup.back',
  NAVIGATE_SUPPORT_PAGE: 'navigate.support.page',
  CLICK_TAKE_TOUR: 'click.take.tour',
  SELET_LANGUAGE: 'select.language',
  NAVIGATE_HOME_PAGE: 'navigate.home.page',
  NAVIGATE_PROFILE: 'navigate.profile.page',
  CLICK_JUMP_START: 'click.jump.start',
  UNIVERSAL_LEARNER_LINKED_ACCOUNT: 'universal.learner.linked.account',
  UNIVERSAL_LEARNER_MAYBE_LATER: 'universal.learner.maybe.later',
  IDENTIFY_MY_ACCOUNT: 'identify.my.account',
  SUBMIT_GRADE_LEVEL: 'submit.grade.level',
  DISMISS_UNIVERSAL_LEARNER_PULLUP: 'dismiss.universal.learner.pullup',
  STUDENT_PLAY_AUDIO: 'student.play.audio',
  STUDENT_SKIP_AUDIO: 'student.skip.audio',
  DATA_VISIBILITY_ON: 'data.visibility.on',
  DATA_VISIBILITY_OFF: 'data.visibility.off',
  ACCESSIBILITY_RESET_BUTTON: 'accessibility.reset.button',
  ACCESSIBILITY_SAVE_BUTTON: 'accessibility.save.button',
  PREFERNCE_SAVE: 'prefernce.save',
  PREFERENCE_CANCEL: 'preference_cancel',
  ACCESS_LEARNING_DATA: 'access.learning.data',
  INVITE_GUARDIAN: 'invite.guardian',
  CLOSE_GUARDIAN_PULLUP: 'close.guardian.pullup',
  ADD_LINKED_ACCOUNT: 'add.linked.account',
  SAVE_ABOUT: 'save.about',
  BACK_PO_TO_DASHBOARD: 'back.po.to.dashboard',
  BACK_COMPETENCY_GAIN_TO_DASHBOARD: 'back.competency.gain.to.dashboard',
  CLICK_DASHBOARD_RESUME_STUDY: 'click.dashboard.resume.study',
  TAKE_THE_DIAGNOSIC: 'take.the.diagnostic',
  EDIT_MY_LOCATION: 'edit.my.location',
  TAKE_TOUR_BACK: 'take.tour.back',
  DISMISS_TAKE_A_TOUR: 'dismiss.take.a.tour',
  TAKE_TOUR_NEXT: 'take.tour.next',
  CLOSE_PLAYER_CONTAINER: 'close.player.container',
  CLICK_STUDENT_CLASS_ROOM_CARD: 'click.student.class.room.card',
  BACK_CLASS_NAVBAR_TO_HOME: 'back.class.navbar.to.home',
  CLICK_NOTE_TAKING_TOOL: 'click.note.taking.tool',
  PREFERENCE_CHOOSE_SUBJECT: 'preference.choose.subject',
  PREFERENCE_PRIMARY_PREFER_LANGUAGE: 'preference.primary.prefer.language',
  PREFERENCE_PREFERRED_LANGUAGE: 'preference.preferred.language',
  PREFERENCE_ADD_NEW_CATEGORY: 'preference.add.new.category',
  CLICK_PREFERENCE_EDIT: 'click.preference.edit',
  PROFILE_ABOVE_SELECT_COUNTRY: 'profile.above.select.country',
  PROFILE_ABOUT_UPLOAD_IMAGE: 'profile.about.upload.image',
  PROFILE_ABOUT_REMOVE_IMAGE: 'profile.about.remove.image',
  CLICK_GOORU_LOGO_NAVIGATE_HOME_PAGE: 'click.gooru.logo.navigate.home.page',
  COMPLETION_MASTER_COUNT: 'completion.master.count',
  VIEW_YOUR_SKYLINE: 'view.your.skyline',
  CLOSE_STUDY_VOW: 'close.study.now'
};

export const APP_ID = 'NavigatorWeb';

export const OS_LIST = [
  { name: 'Windows Phone', value: 'Windows Phone', version: 'OS' },
  { name: 'Windows', value: 'Win', version: 'NT' },
  { name: 'iPhone', value: 'iPhone', version: 'OS' },
  { name: 'iPad', value: 'iPad', version: 'OS' },
  { name: 'Kindle', value: 'Silk', version: 'Silk' },
  { name: 'Android', value: 'Android', version: 'Android' },
  { name: 'PlayBook', value: 'PlayBook', version: 'OS' },
  { name: 'BlackBerry', value: 'BlackBerry', version: '/' },
  { name: 'Macintosh', value: 'Mac', version: 'OS X' },
  { name: 'Linux', value: 'Linux', version: 'rv' },
  { name: 'Palm', value: 'Palm', version: 'PalmOS' }
];

export const BROWSER_LIST = [
  { name: 'Chrome', value: 'Chrome', version: 'Chrome' },
  { name: 'Firefox', value: 'Firefox', version: 'Firefox' },
  { name: 'Safari', value: 'Safari', version: 'Version' },
  { name: 'Internet Explorer', value: 'MSIE', version: 'MSIE' },
  { name: 'Opera', value: 'Opera', version: 'Opera' },
  { name: 'BlackBerry', value: 'CLDC', version: 'CLDC' },
  { name: 'Mozilla', value: 'Mozilla', version: 'Mozilla' }
];
